language: go

branches:
  only:
  - master

go:
  - "1.x" # use the latest Go release

env:
  - GO111MODULE=on

stages:
  - test
  - name: release

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.18.0

script:
  - golangci-lint run ./...
  - go test

jobs:
  include:
    - stage: test
    - stage: release
      before_install: skip
      before_script: skip
      install: skip
      script: skip
      before_deploy:
        - go get -u github.com/hugoArregui/semantic-release/cmd/travis
        - echo $GOPATH
      deploy:
        provider: script
        skip_cleanup: true
        script: "$GOPATH/bin/travis"
